/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./app/**/*.{js,jsx,ts,tsx}", "./components/**/*.{js,jsx,ts,tsx}"],
  presets: [require("nativewind/preset")],
  theme: {
    extend: {
      colors: {
        "surface-container-high": "#ebe8e3",
        "secondary": "#6e5c40",
        "error-container": "#ffdad6",
        "on-error": "#ffffff",
        "secondary-container": "#f8dfbb",
        "on-secondary-fixed-variant": "#55442a",
        "tertiary-container": "#332c1f",
        "secondary-fixed-dim": "#dbc3a1",
        "on-secondary-container": "#746245",
        "tertiary-fixed": "#eee1cd",
        "primary": "#181919",
        "tertiary-fixed-dim": "#d1c5b2",
        "surface": "#fcf9f4",
        "inverse-surface": "#31302d",
        "primary-fixed-dim": "#c8c6c6",
        "on-primary-container": "#959494",
        "on-primary-fixed": "#1b1c1c",
        "on-primary-fixed-variant": "#474747",
        "on-error-container": "#93000a",
        "on-secondary": "#ffffff",
        "on-tertiary-fixed": "#211b0f",
        "error": "#ba1a1a",
        "outline": "#747878",
        "secondary-fixed": "#f8dfbb",
        "surface-container-highest": "#e5e2dd",
        "surface-tint": "#5f5e5e",
        "on-background": "#1c1c19",
        "surface-bright": "#fcf9f4",
        "primary-container": "#2d2d2d",
        "surface-container": "#f0ede8",
        "on-surface": "#1c1c19",
        "on-tertiary-fixed-variant": "#4e4637",
        "primary-fixed": "#e4e2e1",
        "outline-variant": "#c4c7c7",
        "on-tertiary-container": "#9d9382",
        "on-surface-variant": "#444748",
        "background": "#fcf9f4",
        "surface-container-low": "#f6f3ee",
        "tertiary": "#1d180c",
        "on-primary": "#ffffff",
        "inverse-on-surface": "#f3f0eb",
        "on-tertiary": "#ffffff",
        "surface-dim": "#dcdad5",
        "inverse-primary": "#c8c6c6",
        "on-secondary-fixed": "#261904",
        "surface-container-lowest": "#ffffff",
        "surface-variant": "#e5e2dd"
      },
      fontFamily: {
        "eb-garamond": ["EBGaramond-Regular"],
        "eb-garamond-medium": ["EBGaramond-Medium"],
        "hanken-grotesk": ["HankenGrotesk-Regular"],
        "hanken-grotesk-medium": ["HankenGrotesk-Medium"],
        "hanken-grotesk-semibold": ["HankenGrotesk-SemiBold"],
      }
    },
  },
  plugins: [],
}
